version: "3"
services:
  mongo01:
    image: mongo:3.6
    hostname: mongo01
    command: mongod --replSet rs1 --port 27017 --storageEngine wiredTiger --auth --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - ./scripts/replset:/docker-entrypoint-initdb.d
      - ./keyFile:/opt/keyFile
  mongo02:
    image: mongo:3.6
    hostname: mongo02
    command: mongod --replSet rs1 --port 27017 --storageEngine wiredTiger --auth --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - ./scripts/replset:/docker-entrypoint-initdb.d
      - ./keyFile:/opt/keyFile
  mongo03:
    image: mongo:3.6
    hostname: mongo03
    command: mongod --replSet rs1 --port 27017 --storageEngine wiredTiger --auth --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - ./scripts/replset:/docker-entrypoint-initdb.d
      - ./keyFile:/opt/keyFile